In [1]:
import os
import yaml
import pandas as pd
import matplotlib.pyplot as plt
import time
import seaborn as sns  # optional, just for color if you like
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
import statsmodels.formula.api as smf

In [14]:
base_dir = "/Users/seohyon/resources/results"

keep_methods = [
    "embed_cell_types_jittered",
    "embed_cell_types",
    "shuffle_integration",
    "shuffle_integration_by_cell_type",
    "shuffle_integration",
    "scanvi",
    "combat",
    "scvi",
    "harmony",
    "harmonypy",
    "batchelor_fastmnn",
    "liger",
    "pyliger",
    "scalex",
    "uce",
    "no_integration",
    "no_integration_batch",
    "scanorama"
]

dfs_by_folder = {}   # <--- NEW: store one DF per folder

# Step 1 — Collect rows per folder
for folder in os.listdir(base_dir):
    folder_path = os.path.join(base_dir, folder)
    yaml_path = os.path.join(folder_path, "score_uns.yaml")

    # only process valid run folders
    if not (os.path.isdir(folder_path) and os.path.exists(yaml_path)):
        continue

    folder_rows = []     # rows only for this folder

    with open(yaml_path, "r") as f:
        try:
            data = yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"⚠️ Could not read {yaml_path}: {e}")
            continue

    for entry in data:
        method = entry.get("method_id", "").strip().lower()
        if method not in keep_methods:
            continue

        metrics = entry.get("metric_ids", [])
        values = entry.get("metric_values", [])

        for m_id, m_val in zip(metrics, values):
            folder_rows.append({
                "dataset_id": entry.get("dataset_id"),
                "file_size": entry.get("file_size"),
                "method_id": method,
                "normalization_id": entry.get("normalization_id"),
                "metric_id": m_id,
                "metric_value": m_val,
                "run_folder": folder,     # optional: keep source folder
            })

    # Step 2 — create DataFrame for this folder
    df_folder = pd.DataFrame(folder_rows)
    df_folder = df_folder.dropna(subset=["metric_value"]).copy()
    df_folder = df_folder[~df_folder["metric_id"].isin(["kbet", "hvg_overlap"])].copy() # drop unwanted metrics
    df_folder["dataset_id"] = df_folder["dataset_id"].str.split("/").str[-1] # clean the dataset id

    dfs_by_folder[folder] = df_folder   # store it

dfs_by_folder = dict(sorted(dfs_by_folder.items())) # sort by date

In [15]:
for name, df_run in dfs_by_folder.items():
    print(name, df_run.groupby("metric_id").size())

run_2025-01-11_14-07-39 metric_id
ari                        93
asw_batch                  93
asw_label                  89
cell_cycle_conservation    45
clisi                      92
graph_connectivity         93
ilisi                      92
isolated_label_asw         91
isolated_label_f1          76
nmi                        93
pcr                        91
dtype: int64
run_2025-01-20_15-57-21 metric_id
ari                        92
asw_batch                  92
asw_label                  87
cell_cycle_conservation    88
clisi                      91
graph_connectivity         93
ilisi                      91
isolated_label_asw         66
isolated_label_f1          76
nmi                        92
pcr                        93
dtype: int64
run_2025-01-21_17-26-56 metric_id
ari                        89
asw_batch                  89
asw_label                  82
cell_cycle_conservation    89
clisi                      86
graph_connectivity         89
ilisi                      86
isolated_label_asw         67
isolated_label_f1          73
nmi                        89
pcr                        89
dtype: int64
run_2025-01-23_18-03-16 metric_id
ari                        102
asw_batch                  102
asw_label                  101
cell_cycle_conservation    102
clisi                      102
graph_connectivity         102
ilisi                      102
isolated_label_asw          85
isolated_label_f1           85
nmi                        102
pcr                        102
dtype: int64
run_2025-07-28_16-56-15 metric_id
ari                        18
asw_batch                  18
asw_label                  18
cell_cycle_conservation    18
clisi                      18
graph_connectivity         18
ilisi                      18
isolated_label_asw         15
isolated_label_f1          15
kbet_pg                    18
kbet_pg_label              18
nmi                        18
pcr                        18
dtype: int64
run_2025-07-29_12-58-29 metric_id
ari                        48
asw_batch                  48
asw_label                  48
cell_cycle_conservation    48
clisi                      48
graph_connectivity         48
ilisi                      48
isolated_label_asw         40
isolated_label_f1          40
kbet_pg                    48
kbet_pg_label              48
nmi                        48
pcr                        48
dtype: int64
run_2025-08-13_18-16-48 metric_id
ari                        102
asw_batch                  102
asw_label                   98
cell_cycle_conservation    102
clisi                      102
graph_connectivity         102
ilisi                      102
isolated_label_asw          79
isolated_label_f1           85
kbet_pg                    102
kbet_pg_label              102
nmi                        102
pcr                        102
dtype: int64
run_2025-10-11_13-28-50 metric_id
ari                        102
ari_batch                  102
asw_batch                  102
asw_label                  102
cell_cycle_conservation    102
clisi                      102
graph_connectivity         102
ilisi                      102
isolated_label_asw          85
isolated_label_f1           85
kbet_pg                    102
kbet_pg_label              102
nmi                        102
nmi_batch                  102
pcr                        102
dtype: int64

In [25]:
for name, df_run in dfs_by_folder.items():
    print(name, df_run.groupby(["metric_id", "method_id"]).size().unique())

run_2025-01-11_14-07-39 [6 5 1 4 3 2]
run_2025-01-20_15-57-21 [6 5 4 1 2 3]
run_2025-01-21_17-26-56 [6 4 5 2 3 1]
run_2025-01-23_18-03-16 [6 5]
run_2025-07-28_16-56-15 [6 5]
run_2025-07-29_12-58-29 [6 5]
run_2025-08-13_18-16-48 [6 5 4]
run_2025-10-11_13-28-50 [6 5]

In [28]:
for name, df_run in dfs_by_folder.items():
    print(f"\n===== {name} =====")
    group_df = (
        df_run.groupby(["metric_id", "method_id"])
              .size()
              .reset_index(name="count")
              .sort_values(["metric_id", "method_id"])
    )
    print(group_df.to_string(index=False))

===== run_2025-01-11_14-07-39 =====
              metric_id                        method_id  count
                    ari                batchelor_fastmnn      6
                    ari                           combat      6
                    ari                 embed_cell_types      6
                    ari        embed_cell_types_jittered      6
                    ari                          harmony      6
                    ari                        harmonypy      6
                    ari                            liger      5
                    ari                   no_integration      6
                    ari             no_integration_batch      5
                    ari                          pyliger      6
                    ari                           scalex      5
                    ari                        scanorama      5
                    ari                           scanvi      6
                    ari                             scvi      6
                    ari              shuffle_integration      6
                    ari shuffle_integration_by_cell_type      6
                    ari                              uce      1
              asw_batch                batchelor_fastmnn      6
              asw_batch                           combat      6
              asw_batch                 embed_cell_types      6
              asw_batch        embed_cell_types_jittered      6
              asw_batch                          harmony      6
              asw_batch                        harmonypy      6
              asw_batch                            liger      5
              asw_batch                   no_integration      6
              asw_batch             no_integration_batch      5
              asw_batch                          pyliger      6
              asw_batch                           scalex      5
              asw_batch                        scanorama      5
              asw_batch                           scanvi      6
              asw_batch                             scvi      6
              asw_batch              shuffle_integration      6
              asw_batch shuffle_integration_by_cell_type      6
              asw_batch                              uce      1
              asw_label                batchelor_fastmnn      6
              asw_label                           combat      6
              asw_label                 embed_cell_types      6
              asw_label        embed_cell_types_jittered      6
              asw_label                          harmony      6
              asw_label                        harmonypy      6
              asw_label                            liger      5
              asw_label                   no_integration      6
              asw_label             no_integration_batch      4
              asw_label                          pyliger      6
              asw_label                           scalex      5
              asw_label                        scanorama      5
              asw_label                           scanvi      4
              asw_label                             scvi      6
              asw_label              shuffle_integration      6
              asw_label shuffle_integration_by_cell_type      6
cell_cycle_conservation                batchelor_fastmnn      3
cell_cycle_conservation                           combat      3
cell_cycle_conservation                 embed_cell_types      3
cell_cycle_conservation        embed_cell_types_jittered      3
cell_cycle_conservation                          harmony      3
cell_cycle_conservation                        harmonypy      3
cell_cycle_conservation                            liger      2
cell_cycle_conservation                   no_integration      3
cell_cycle_conservation             no_integration_batch      3
cell_cycle_conservation                          pyliger      3
cell_cycle_conservation                           scalex      2
cell_cycle_conservation                        scanorama      2
cell_cycle_conservation                           scanvi      3
cell_cycle_conservation                             scvi      3
cell_cycle_conservation              shuffle_integration      3
cell_cycle_conservation shuffle_integration_by_cell_type      3
                  clisi                batchelor_fastmnn      6
                  clisi                           combat      6
                  clisi                 embed_cell_types      6
                  clisi        embed_cell_types_jittered      6
                  clisi                          harmony      6
                  clisi                        harmonypy      6
                  clisi                            liger      5
                  clisi                   no_integration      5
                  clisi             no_integration_batch      5
                  clisi                          pyliger      6
                  clisi                           scalex      5
                  clisi                        scanorama      5
                  clisi                           scanvi      6
                  clisi                             scvi      6
                  clisi              shuffle_integration      6
                  clisi shuffle_integration_by_cell_type      6
                  clisi                              uce      1
     graph_connectivity                batchelor_fastmnn      6
     graph_connectivity                           combat      6
     graph_connectivity                 embed_cell_types      6
     graph_connectivity        embed_cell_types_jittered      6
     graph_connectivity                          harmony      6
     graph_connectivity                        harmonypy      6
     graph_connectivity                            liger      5
     graph_connectivity                   no_integration      6
     graph_connectivity             no_integration_batch      5
     graph_connectivity                          pyliger      6
     graph_connectivity                           scalex      5
     graph_connectivity                        scanorama      5
     graph_connectivity                           scanvi      6
     graph_connectivity                             scvi      6
     graph_connectivity              shuffle_integration      6
     graph_connectivity shuffle_integration_by_cell_type      6
     graph_connectivity                              uce      1
                  ilisi                batchelor_fastmnn      6
                  ilisi                           combat      6
                  ilisi                 embed_cell_types      6
                  ilisi        embed_cell_types_jittered      6
                  ilisi                          harmony      6
                  ilisi                        harmonypy      6
                  ilisi                            liger      5
                  ilisi                   no_integration      5
                  ilisi             no_integration_batch      5
                  ilisi                          pyliger      6
                  ilisi                           scalex      5
                  ilisi                        scanorama      5
                  ilisi                           scanvi      6
                  ilisi                             scvi      6
                  ilisi              shuffle_integration      6
                  ilisi shuffle_integration_by_cell_type      6
                  ilisi                              uce      1
     isolated_label_asw                batchelor_fastmnn      6
     isolated_label_asw                           combat      6
     isolated_label_asw                 embed_cell_types      6
     isolated_label_asw        embed_cell_types_jittered      6
     isolated_label_asw                          harmony      6
     isolated_label_asw                        harmonypy      6
     isolated_label_asw                            liger      5
     isolated_label_asw                   no_integration      6
     isolated_label_asw             no_integration_batch      5
     isolated_label_asw                          pyliger      6
     isolated_label_asw                           scalex      5
     isolated_label_asw                        scanorama      5
     isolated_label_asw                           scanvi      5
     isolated_label_asw                             scvi      5
     isolated_label_asw              shuffle_integration      6
     isolated_label_asw shuffle_integration_by_cell_type      6
     isolated_label_asw                              uce      1
      isolated_label_f1                batchelor_fastmnn      5
      isolated_label_f1                           combat      5
      isolated_label_f1                 embed_cell_types      5
      isolated_label_f1        embed_cell_types_jittered      5
      isolated_label_f1                          harmony      5
      isolated_label_f1                        harmonypy      5
      isolated_label_f1                            liger      4
      isolated_label_f1                   no_integration      5
      isolated_label_f1             no_integration_batch      4
      isolated_label_f1                          pyliger      5
      isolated_label_f1                           scalex      4
      isolated_label_f1                        scanorama      4
      isolated_label_f1                           scanvi      5
      isolated_label_f1                             scvi      5
      isolated_label_f1              shuffle_integration      5
      isolated_label_f1 shuffle_integration_by_cell_type      5
                    nmi                batchelor_fastmnn      6
                    nmi                           combat      6
                    nmi                 embed_cell_types      6
                    nmi        embed_cell_types_jittered      6
                    nmi                          harmony      6
                    nmi                        harmonypy      6
                    nmi                            liger      5
                    nmi                   no_integration      6
                    nmi             no_integration_batch      5
                    nmi                          pyliger      6
                    nmi                           scalex      5
                    nmi                        scanorama      5
                    nmi                           scanvi      6
                    nmi                             scvi      6
                    nmi              shuffle_integration      6
                    nmi shuffle_integration_by_cell_type      6
                    nmi                              uce      1
                    pcr                batchelor_fastmnn      6
                    pcr                           combat      6
                    pcr                 embed_cell_types      6
                    pcr        embed_cell_types_jittered      6
                    pcr                          harmony      6
                    pcr                        harmonypy      5
                    pcr                            liger      5
                    pcr                   no_integration      5
                    pcr             no_integration_batch      5
                    pcr                          pyliger      6
                    pcr                           scalex      5
                    pcr                        scanorama      5
                    pcr                           scanvi      6
                    pcr                             scvi      6
                    pcr              shuffle_integration      6
                    pcr shuffle_integration_by_cell_type      6
                    pcr                              uce      1

===== run_2025-01-20_15-57-21 =====
              metric_id                        method_id  count
                    ari                batchelor_fastmnn      6
                    ari                           combat      6
                    ari                 embed_cell_types      6
                    ari        embed_cell_types_jittered      6
                    ari                          harmony      5
                    ari                        harmonypy      6
                    ari                            liger      4
                    ari                   no_integration      6
                    ari             no_integration_batch      6
                    ari                          pyliger      4
                    ari                           scalex      6
                    ari                        scanorama      6
                    ari                           scanvi      6
                    ari                             scvi      6
                    ari              shuffle_integration      6
                    ari shuffle_integration_by_cell_type      6
                    ari                              uce      1
              asw_batch                batchelor_fastmnn      6
              asw_batch                           combat      6
              asw_batch                 embed_cell_types      4
              asw_batch        embed_cell_types_jittered      5
              asw_batch                          harmony      6
              asw_batch                        harmonypy      6
              asw_batch                            liger      6
              asw_batch                   no_integration      6
              asw_batch             no_integration_batch      6
              asw_batch                          pyliger      4
              asw_batch                           scalex      6
              asw_batch                        scanorama      6
              asw_batch                           scanvi      6
              asw_batch                             scvi      6
              asw_batch              shuffle_integration      6
              asw_batch shuffle_integration_by_cell_type      6
              asw_batch                              uce      1
              asw_label                batchelor_fastmnn      6
              asw_label                           combat      6
              asw_label                 embed_cell_types      4
              asw_label        embed_cell_types_jittered      6
              asw_label                          harmony      6
              asw_label                        harmonypy      5
              asw_label                            liger      6
              asw_label                   no_integration      5
              asw_label             no_integration_batch      6
              asw_label                          pyliger      4
              asw_label                           scalex      6
              asw_label                        scanorama      6
              asw_label                           scanvi      5
              asw_label                             scvi      5
              asw_label              shuffle_integration      5
              asw_label shuffle_integration_by_cell_type      5
              asw_label                              uce      1
cell_cycle_conservation                batchelor_fastmnn      6
cell_cycle_conservation                           combat      6
cell_cycle_conservation                 embed_cell_types      4
cell_cycle_conservation        embed_cell_types_jittered      5
cell_cycle_conservation                          harmony      6
cell_cycle_conservation                        harmonypy      6
cell_cycle_conservation                            liger      2
cell_cycle_conservation                   no_integration      6
cell_cycle_conservation             no_integration_batch      6
cell_cycle_conservation                          pyliger      4
cell_cycle_conservation                           scalex      6
cell_cycle_conservation                        scanorama      6
cell_cycle_conservation                           scanvi      6
cell_cycle_conservation                             scvi      6
cell_cycle_conservation              shuffle_integration      6
cell_cycle_conservation shuffle_integration_by_cell_type      6
cell_cycle_conservation                              uce      1
                  clisi                batchelor_fastmnn      6
                  clisi                           combat      6
                  clisi                 embed_cell_types      4
                  clisi        embed_cell_types_jittered      6
                  clisi                          harmony      5
                  clisi                        harmonypy      6
                  clisi                            liger      5
                  clisi                   no_integration      6
                  clisi             no_integration_batch      6
                  clisi                          pyliger      4
                  clisi                           scalex      6
                  clisi                        scanorama      6
                  clisi                           scanvi      6
                  clisi                             scvi      6
                  clisi              shuffle_integration      6
                  clisi shuffle_integration_by_cell_type      6
                  clisi                              uce      1
     graph_connectivity                batchelor_fastmnn      6
     graph_connectivity                           combat      6
     graph_connectivity                 embed_cell_types      5
     graph_connectivity        embed_cell_types_jittered      6
     graph_connectivity                          harmony      6
     graph_connectivity                        harmonypy      6
     graph_connectivity                            liger      5
     graph_connectivity                   no_integration      6
     graph_connectivity             no_integration_batch      6
     graph_connectivity                          pyliger      4
     graph_connectivity                           scalex      6
     graph_connectivity                        scanorama      6
     graph_connectivity                           scanvi      6
     graph_connectivity                             scvi      6
     graph_connectivity              shuffle_integration      6
     graph_connectivity shuffle_integration_by_cell_type      6
     graph_connectivity                              uce      1
                  ilisi                batchelor_fastmnn      6
                  ilisi                           combat      6
                  ilisi                 embed_cell_types      4
                  ilisi        embed_cell_types_jittered      6
                  ilisi                          harmony      5
                  ilisi                        harmonypy      6
                  ilisi                            liger      5
                  ilisi                   no_integration      6
                  ilisi             no_integration_batch      6
                  ilisi                          pyliger      4
                  ilisi                           scalex      6
                  ilisi                        scanorama      6
                  ilisi                           scanvi      6
                  ilisi                             scvi      6
                  ilisi              shuffle_integration      6
                  ilisi shuffle_integration_by_cell_type      6
                  ilisi                              uce      1
     isolated_label_asw                batchelor_fastmnn      4
     isolated_label_asw                           combat      3
     isolated_label_asw                 embed_cell_types      5
     isolated_label_asw        embed_cell_types_jittered      4
     isolated_label_asw                          harmony      5
     isolated_label_asw                        harmonypy      3

In [31]:
for name, df_run in dfs_by_folder.items():
    print(f"\n===== {name} =====")
    grouped = df_run.groupby("metric_id")["method_id"].unique()

    for metric, methods in grouped.items():
        print(metric, len(list(methods)))

===== run_2025-01-11_14-07-39 =====
ari 17
asw_batch 17
asw_label 16
cell_cycle_conservation 16
clisi 17
graph_connectivity 17
ilisi 17
isolated_label_asw 17
isolated_label_f1 16
nmi 17
pcr 17

===== run_2025-01-20_15-57-21 =====
ari 17
asw_batch 17
asw_label 17
cell_cycle_conservation 17
clisi 17
graph_connectivity 17
ilisi 17
isolated_label_asw 16
isolated_label_f1 16
nmi 17
pcr 17

===== run_2025-01-21_17-26-56 =====
ari 16
asw_batch 16
asw_label 16
cell_cycle_conservation 16
clisi 16
graph_connectivity 16
ilisi 16
isolated_label_asw 16
isolated_label_f1 16
nmi 16
pcr 16

===== run_2025-01-23_18-03-16 =====
ari 17
asw_batch 17
asw_label 17
cell_cycle_conservation 17
clisi 17
graph_connectivity 17
ilisi 17
isolated_label_asw 17
isolated_label_f1 17
nmi 17
pcr 17

===== run_2025-07-28_16-56-15 =====
ari 3
asw_batch 3
asw_label 3
cell_cycle_conservation 3
clisi 3
graph_connectivity 3
ilisi 3
isolated_label_asw 3
isolated_label_f1 3
kbet_pg 3
kbet_pg_label 3
nmi 3
pcr 3

===== run_2025-07-29_12-58-29 =====
ari 8
asw_batch 8
asw_label 8
cell_cycle_conservation 8
clisi 8
graph_connectivity 8
ilisi 8
isolated_label_asw 8
isolated_label_f1 8
kbet_pg 8
kbet_pg_label 8
nmi 8
pcr 8

===== run_2025-08-13_18-16-48 =====
ari 17
asw_batch 17
asw_label 17
cell_cycle_conservation 17
clisi 17
graph_connectivity 17
ilisi 17
isolated_label_asw 17
isolated_label_f1 17
kbet_pg 17
kbet_pg_label 17
nmi 17
pcr 17

===== run_2025-10-11_13-28-50 =====
ari 17
ari_batch 17
asw_batch 17
asw_label 17
cell_cycle_conservation 17
clisi 17
graph_connectivity 17
ilisi 17
isolated_label_asw 17
isolated_label_f1 17
kbet_pg 17
kbet_pg_label 17
nmi 17
nmi_batch 17
pcr 17

In [35]:
for name, df_run in dfs_by_folder.items():
    print(f"\n===== {name} =====")
    grouped = df_run.groupby("metric_id")["dataset_id"].unique()

    for metric, datasets in grouped.items():
        print(metric, len(list(datasets)))

===== run_2025-01-11_14-07-39 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 3
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 6
isolated_label_f1 5
nmi 6
pcr 6

===== run_2025-01-20_15-57-21 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
nmi 6
pcr 6

===== run_2025-01-21_17-26-56 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
nmi 6
pcr 6

===== run_2025-01-23_18-03-16 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
nmi 6
pcr 6

===== run_2025-07-28_16-56-15 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
kbet_pg 6
kbet_pg_label 6
nmi 6
pcr 6

===== run_2025-07-29_12-58-29 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
kbet_pg 6
kbet_pg_label 6
nmi 6
pcr 6

===== run_2025-08-13_18-16-48 =====
ari 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
kbet_pg 6
kbet_pg_label 6
nmi 6
pcr 6

===== run_2025-10-11_13-28-50 =====
ari 6
ari_batch 6
asw_batch 6
asw_label 6
cell_cycle_conservation 6
clisi 6
graph_connectivity 6
ilisi 6
isolated_label_asw 5
isolated_label_f1 5
kbet_pg 6
kbet_pg_label 6
nmi 6
nmi_batch 6
pcr 6

In [45]:
dfs_by_folder["run_2025-01-11_14-07-39"].query("metric_id == 'cell_cycle_conservation'")["dataset_id"].unique()

array(['immune_cell_atlas', 'tabula_sapiens', 'mouse_pancreas_atlas'],
      dtype=object)

In [41]:
for name, df_run in dfs_by_folder.items():
    print(f"\n===== {name} =====")
    filtered = df_run.query("metric_id in ['isolated_label_asw', 'isolated_label_f1']")
    grouped = filtered.groupby("metric_id")["dataset_id"].unique()


    for metric, datasets in grouped.items():
        print(metric, sorted(list(datasets)))

===== run_2025-01-11_14-07-39 =====
isolated_label_asw ['dkd', 'gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-01-20_15-57-21 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-01-21_17-26-56 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-01-23_18-03-16 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-07-28_16-56-15 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-07-29_12-58-29 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-08-13_18-16-48 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

===== run_2025-10-11_13-28-50 =====
isolated_label_asw ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']
isolated_label_f1 ['gtex_v9', 'hypomap', 'immune_cell_atlas', 'mouse_pancreas_atlas', 'tabula_sapiens']

In [46]:
big_df = pd.concat(dfs_by_folder.values(), axis=0, ignore_index=True)

In [54]:
# Count per metric + method + dataset
group_counts = (
    big_df.groupby(["metric_id", "method_id", "dataset_id"])
      .size()
      .reset_index(name="count")
)

# Compute min count *per metric_id + method_id* 
group_counts["min_count"] = (
    group_counts
    .groupby(["metric_id", "method_id"])["count"]
    .transform("min")
)

per_method_min = (
    group_counts[["metric_id", "method_id", "min_count"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(per_method_min.to_string())

                   metric_id                         method_id  min_count
0                        ari                 batchelor_fastmnn          6
1                        ari                            combat          6
2                        ari                  embed_cell_types          7
3                        ari         embed_cell_types_jittered          6
4                        ari                           harmony          5
5                        ari                         harmonypy          8
6                        ari                             liger          5
7                        ari                    no_integration          7
8                        ari              no_integration_batch          6
9                        ari                           pyliger          4
10                       ari                            scalex          4
11                       ari                         scanorama          7
12                       ari                            scanvi          6
13                       ari                              scvi          8
14                       ari               shuffle_integration          7
15                       ari  shuffle_integration_by_cell_type          7
16                       ari                               uce          3
17                 ari_batch                 batchelor_fastmnn          1
18                 ari_batch                            combat          1
19                 ari_batch                  embed_cell_types          1
20                 ari_batch         embed_cell_types_jittered          1
21                 ari_batch                           harmony          1
22                 ari_batch                         harmonypy          1
23                 ari_batch                             liger          1
24                 ari_batch                    no_integration          1
25                 ari_batch              no_integration_batch          1
26                 ari_batch                           pyliger          1
27                 ari_batch                            scalex          1
28                 ari_batch                         scanorama          1
29                 ari_batch                            scanvi          1
30                 ari_batch                              scvi          1
31                 ari_batch               shuffle_integration          1
32                 ari_batch  shuffle_integration_by_cell_type          1
33                 ari_batch                               uce          1
34                 asw_batch                 batchelor_fastmnn          6
35                 asw_batch                            combat          6
36                 asw_batch                  embed_cell_types          6
37                 asw_batch         embed_cell_types_jittered          5
38                 asw_batch                           harmony          6
39                 asw_batch                         harmonypy          8
40                 asw_batch                             liger          5
41                 asw_batch                    no_integration          7
42                 asw_batch              no_integration_batch          6
43                 asw_batch                           pyliger          4
44                 asw_batch                            scalex          4
45                 asw_batch                         scanorama          7
46                 asw_batch                            scanvi          6
47                 asw_batch                              scvi          8
48                 asw_batch               shuffle_integration          7
49                 asw_batch  shuffle_integration_by_cell_type          7
50                 asw_batch                               uce          3
51                 asw_label                 batchelor_fastmnn          6
52                 asw_label                            combat          6
53                 asw_label                  embed_cell_types          5
54                 asw_label         embed_cell_types_jittered          6
55                 asw_label                           harmony          6
56                 asw_label                         harmonypy          7
57                 asw_label                             liger          5
58                 asw_label                    no_integration          5
59                 asw_label              no_integration_batch          6
60                 asw_label                           pyliger          4
61                 asw_label                            scalex          4
62                 asw_label                         scanorama          7
63                 asw_label                            scanvi          4
64                 asw_label                              scvi          7
65                 asw_label               shuffle_integration          5
66                 asw_label  shuffle_integration_by_cell_type          6
67                 asw_label                               uce          1
68   cell_cycle_conservation                 batchelor_fastmnn          5
69   cell_cycle_conservation                            combat          5
70   cell_cycle_conservation                  embed_cell_types          6
71   cell_cycle_conservation         embed_cell_types_jittered          4
72   cell_cycle_conservation                           harmony          5
73   cell_cycle_conservation                         harmonypy          7
74   cell_cycle_conservation                             liger          4
75   cell_cycle_conservation                    no_integration          6
76   cell_cycle_conservation              no_integration_batch          6
77   cell_cycle_conservation                           pyliger          3
78   cell_cycle_conservation                            scalex          4
79   cell_cycle_conservation                         scanorama          7
80   cell_cycle_conservation                            scanvi          5
81   cell_cycle_conservation                              scvi          7
82   cell_cycle_conservation               shuffle_integration          6
83   cell_cycle_conservation  shuffle_integration_by_cell_type          6
84   cell_cycle_conservation                               uce          3
85                     clisi                 batchelor_fastmnn          6
86                     clisi                            combat          6
87                     clisi                  embed_cell_types          6
88                     clisi         embed_cell_types_jittered          5
89                     clisi                           harmony          5
90                     clisi                         harmonypy          8
91                     clisi                             liger          5
92                     clisi                    no_integration          6
93                     clisi              no_integration_batch          6
94                     clisi                           pyliger          4
95                     clisi                            scalex          4
96                     clisi                         scanorama          7
97                     clisi                            scanvi          6
98                     clisi                              scvi          8
99                     clisi               shuffle_integration          6
100                    clisi  shuffle_integration_by_cell_type          7
101                    clisi                               uce          3
102       graph_connectivity                 batchelor_fastmnn          6
103       graph_connectivity                            combat          6
104       graph_connectivity                  embed_cell_types          6
105       graph_connectivity         embed_cell_types_jittered          6
106       graph_connectivity                           harmony          6
107       graph_connectivity                         harmonypy          8
108       graph_connectivity                             liger          5
109       graph_connectivity                    no_integration          7
110       graph_connectivity              no_integration_batch          6
111       graph_connectivity                           pyliger          4
112       graph_connectivity                            scalex          4
113       graph_connectivity                         scanorama          7
114       graph_connectivity                            scanvi          6
115       graph_connectivity                              scvi          8
116       graph_connectivity               shuffle_integration          7
117       graph_connectivity  shuffle_integration_by_cell_type          7
118       graph_connectivity                               uce          3
119                    ilisi                 batchelor_fastmnn          6
120                    ilisi                            combat          6
121                    ilisi                  embed_cell_types          6
122                    ilisi         embed_cell_types_jittered          5
123                    ilisi                           harmony          5
124                    ilisi                         harmonypy          8
125                    ilisi                             liger          5
126                    ilisi                    no_integration          6
127                    ilisi              no_integration_batch          6
128                    ilisi                           pyliger          4
129                    ilisi                            scalex          4
130                    ilisi                         scanorama          7
131                    ilisi                            scanvi          6
132                    ilisi                              scvi          8
133                    ilisi               shuffle_integration          6
134                    ilisi  shuffle_integration_by_cell_type          7
135                    ilisi                               uce          3
136       isolated_label_asw                 batchelor_fastmnn          1
137       isolated_label_asw                            combat          1
138       isolated_label_asw                  embed_cell_types          1
139       isolated_label_asw         embed_cell_types_jittered          1
140       isolated_label_asw                           harmony          1
141       isolated_label_asw                         harmonypy          1
142       isolated_label_asw                             liger          1
143       isolated_label_asw                    no_integration          1
144       isolated_label_asw              no_integration_batch          1
145       isolated_label_asw                           pyliger          1
146       isolated_label_asw                            scalex          1
147       isolated_label_asw                         scanorama          1
148       isolated_label_asw                            scanvi          1
149       isolated_label_asw                              scvi          1
150       isolated_label_asw               shuffle_integration          1
151       isolated_label_asw  shuffle_integration_by_cell_type          1
152       isolated_label_asw                               uce          1
153        isolated_label_f1                 batchelor_fastmnn          6
154        isolated_label_f1                            combat          6
155        isolated_label_f1                  embed_cell_types          6
156        isolated_label_f1         embed_cell_types_jittered          5
157        isolated_label_f1                           harmony          6
158        isolated_label_f1                         harmonypy          8
159        isolated_label_f1                             liger          5
160        isolated_label_f1                    no_integration          7
161        isolated_label_f1              no_integration_batch          6
162        isolated_label_f1                           pyliger          4
163        isolated_label_f1                            scalex          4
164        isolated_label_f1                         scanorama          7
165        isolated_label_f1                            scanvi          6
166        isolated_label_f1                              scvi          8
167        isolated_label_f1               shuffle_integration          7
168        isolated_label_f1  shuffle_integration_by_cell_type          7
169        isolated_label_f1                               uce          3
170                  kbet_pg                 batchelor_fastmnn          2
171                  kbet_pg                            combat          2
172                  kbet_pg                  embed_cell_types          3
173                  kbet_pg         embed_cell_types_jittered          2
174                  kbet_pg                           harmony          2
175                  kbet_pg                         harmonypy          4
176                  kbet_pg                             liger          2
177                  kbet_pg                    no_integration          3
178                  kbet_pg              no_integration_batch          3
179                  kbet_pg                           pyliger          2
180                  kbet_pg                            scalex          2
181                  kbet_pg                         scanorama          4
182                  kbet_pg                            scanvi          2
183                  kbet_pg                              scvi          4
184                  kbet_pg               shuffle_integration          3
185                  kbet_pg  shuffle_integration_by_cell_type          3
186                  kbet_pg                               uce          2
187            kbet_pg_label                 batchelor_fastmnn          2
188            kbet_pg_label                            combat          2
189            kbet_pg_label                  embed_cell_types          3
190            kbet_pg_label         embed_cell_types_jittered          2
191            kbet_pg_label                           harmony          2
192            kbet_pg_label                         harmonypy          4
193            kbet_pg_label                             liger          2
194            kbet_pg_label                    no_integration          3
195            kbet_pg_label              no_integration_batch          3
196            kbet_pg_label                           pyliger          2
197            kbet_pg_label                            scalex          2
198            kbet_pg_label                         scanorama          4
199            kbet_pg_label                            scanvi          2
200            kbet_pg_label                              scvi          4
201            kbet_pg_label               shuffle_integration          3
202            kbet_pg_label  shuffle_integration_by_cell_type          3
203            kbet_pg_label                               uce          2
204                      nmi                 batchelor_fastmnn          6
205                      nmi                            combat          6
206                      nmi                  embed_cell_types          7
207                      nmi         embed_cell_types_jittered          6
208                      nmi                           harmony          5
209                      nmi                         harmonypy          8
210                      nmi                             liger          5
211                      nmi                    no_integration          7
212                      nmi              no_integration_batch          6
213                      nmi                           pyliger          4
214                      nmi                            scalex          4
215                      nmi                         scanorama          7
216                      nmi                            scanvi          6
217                      nmi                              scvi          8
218                      nmi               shuffle_integration          7
219                      nmi  shuffle_integration_by_cell_type          7
220                      nmi                               uce          3
221                nmi_batch                 batchelor_fastmnn          1
222                nmi_batch                            combat          1
223                nmi_batch                  embed_cell_types          1
224                nmi_batch         embed_cell_types_jittered          1
225                nmi_batch                           harmony          1
226                nmi_batch                         harmonypy          1
227                nmi_batch                             liger          1
228                nmi_batch                    no_integration          1
229                nmi_batch              no_integration_batch          1
230                nmi_batch                           pyliger          1
231                nmi_batch                            scalex          1
232                nmi_batch                         scanorama          1
233                nmi_batch                            scanvi          1
234                nmi_batch                              scvi          1
235                nmi_batch               shuffle_integration          1
236                nmi_batch  shuffle_integration_by_cell_type          1
237                nmi_batch                               uce          1
238                      pcr                 batchelor_fastmnn          6
239                      pcr                            combat          6
240                      pcr                  embed_cell_types          6
241                      pcr         embed_cell_types_jittered          6
242                      pcr                           harmony          6
243                      pcr                         harmonypy          7
244                      pcr                             liger          5
245                      pcr                    no_integration          6
246                      pcr              no_integration_batch          6
247                      pcr                           pyliger          4
248                      pcr                            scalex          4
249                      pcr                         scanorama          7
250                      pcr                            scanvi          6
251                      pcr                              scvi          8
252                      pcr               shuffle_integration          7
253                      pcr  shuffle_integration_by_cell_type          7
254                      pcr                               uce          3

In [55]:
per_method_min["min_count"].unique()

array([6, 7, 5, 8, 4, 3, 1, 2])

In [77]:
filtered_df = (
    group_counts
    .query("min_count >= 5")
    .reset_index(drop=True)
)# filtered_df now contains only metric–method pairs where every dataset has ≥ 5 datapoints.

In [80]:
counts = (
    filtered_df
    .groupby(["metric_id", "method_id", "dataset_id"])
    .size()
    .reset_index(name="count")
)

counts

    metric_id                         method_id            dataset_id  count
0         ari                 batchelor_fastmnn                   dkd      1
1         ari                 batchelor_fastmnn               gtex_v9      1
2         ari                 batchelor_fastmnn               hypomap      1
3         ari                 batchelor_fastmnn     immune_cell_atlas      1
4         ari                 batchelor_fastmnn  mouse_pancreas_atlas      1
..        ...                               ...                   ...    ...
803       pcr  shuffle_integration_by_cell_type               gtex_v9      1
804       pcr  shuffle_integration_by_cell_type               hypomap      1
805       pcr  shuffle_integration_by_cell_type     immune_cell_atlas      1
806       pcr  shuffle_integration_by_cell_type  mouse_pancreas_atlas      1
807       pcr  shuffle_integration_by_cell_type        tabula_sapiens      1

[808 rows x 4 columns]

In [81]:
filtered_df[["metric_id", "method_id", "dataset_id", "count"]]

    metric_id                         method_id            dataset_id  count
0         ari                 batchelor_fastmnn                   dkd      6
1         ari                 batchelor_fastmnn               gtex_v9      6
2         ari                 batchelor_fastmnn               hypomap      6
3         ari                 batchelor_fastmnn     immune_cell_atlas      6
4         ari                 batchelor_fastmnn  mouse_pancreas_atlas      6
..        ...                               ...                   ...    ...
803       pcr  shuffle_integration_by_cell_type               gtex_v9      7
804       pcr  shuffle_integration_by_cell_type               hypomap      7
805       pcr  shuffle_integration_by_cell_type     immune_cell_atlas      7
806       pcr  shuffle_integration_by_cell_type  mouse_pancreas_atlas      7
807       pcr  shuffle_integration_by_cell_type        tabula_sapiens      7

[808 rows x 4 columns]

In [85]:
last_run_df = dfs_by_folder["run_2025-10-11_13-28-50"]
# Count per metric + method + dataset
group_counts = (
    last_run_df.groupby(["metric_id", "method_id", "dataset_id"])
      .size()
      .reset_index(name="count")
)

# Compute min count *per metric_id + method_id* 
group_counts["min_count"] = (
    group_counts
    .groupby(["metric_id", "method_id"])["count"]
    .transform("min")
)

last_run_df = (
    group_counts
    #.query("min_count >= 5")
    .reset_index(drop=True)
)
                                             
print(last_run_df[["metric_id", "method_id", "dataset_id", "count"]].to_string())

                    metric_id                         method_id            dataset_id  count
0                         ari                 batchelor_fastmnn                   dkd      1
1                         ari                 batchelor_fastmnn               gtex_v9      1
2                         ari                 batchelor_fastmnn               hypomap      1
3                         ari                 batchelor_fastmnn     immune_cell_atlas      1
4                         ari                 batchelor_fastmnn  mouse_pancreas_atlas      1
5                         ari                 batchelor_fastmnn        tabula_sapiens      1
6                         ari                            combat                   dkd      1
7                         ari                            combat               gtex_v9      1
8                         ari                            combat               hypomap      1
9                         ari                            combat     immune_cell_atlas      1
10                        ari                            combat  mouse_pancreas_atlas      1
11                        ari                            combat        tabula_sapiens      1
12                        ari                  embed_cell_types                   dkd      1
13                        ari                  embed_cell_types               gtex_v9      1
14                        ari                  embed_cell_types               hypomap      1
15                        ari                  embed_cell_types     immune_cell_atlas      1
16                        ari                  embed_cell_types  mouse_pancreas_atlas      1
17                        ari                  embed_cell_types        tabula_sapiens      1
18                        ari         embed_cell_types_jittered                   dkd      1
19                        ari         embed_cell_types_jittered               gtex_v9      1
20                        ari         embed_cell_types_jittered               hypomap      1
21                        ari         embed_cell_types_jittered     immune_cell_atlas      1
22                        ari         embed_cell_types_jittered  mouse_pancreas_atlas      1
23                        ari         embed_cell_types_jittered        tabula_sapiens      1
24                        ari                           harmony                   dkd      1
25                        ari                           harmony               gtex_v9      1
26                        ari                           harmony               hypomap      1
27                        ari                           harmony     immune_cell_atlas      1
28                        ari                           harmony  mouse_pancreas_atlas      1
29                        ari                           harmony        tabula_sapiens      1
30                        ari                         harmonypy                   dkd      1
31                        ari                         harmonypy               gtex_v9      1
32                        ari                         harmonypy               hypomap      1
33                        ari                         harmonypy     immune_cell_atlas      1
34                        ari                         harmonypy  mouse_pancreas_atlas      1
35                        ari                         harmonypy        tabula_sapiens      1
36                        ari                             liger                   dkd      1
37                        ari                             liger               gtex_v9      1
38                        ari                             liger               hypomap      1
39                        ari                             liger     immune_cell_atlas      1
40                        ari                             liger  mouse_pancreas_atlas      1
41                        ari                             liger        tabula_sapiens      1
42                        ari                    no_integration                   dkd      1
43                        ari                    no_integration               gtex_v9      1
44                        ari                    no_integration               hypomap      1
45                        ari                    no_integration     immune_cell_atlas      1
46                        ari                    no_integration  mouse_pancreas_atlas      1
47                        ari                    no_integration        tabula_sapiens      1
48                        ari              no_integration_batch                   dkd      1
49                        ari              no_integration_batch               gtex_v9      1
50                        ari              no_integration_batch               hypomap      1
51                        ari              no_integration_batch     immune_cell_atlas      1
52                        ari              no_integration_batch  mouse_pancreas_atlas      1
53                        ari              no_integration_batch        tabula_sapiens      1
54                        ari                           pyliger                   dkd      1
55                        ari                           pyliger               gtex_v9      1
56                        ari                           pyliger               hypomap      1
57                        ari                           pyliger     immune_cell_atlas      1
58                        ari                           pyliger  mouse_pancreas_atlas      1
59                        ari                           pyliger        tabula_sapiens      1
60                        ari                            scalex                   dkd      1
61                        ari                            scalex               gtex_v9      1
62                        ari                            scalex               hypomap      1
63                        ari                            scalex     immune_cell_atlas      1
64                        ari                            scalex  mouse_pancreas_atlas      1
65                        ari                            scalex        tabula_sapiens      1
66                        ari                         scanorama                   dkd      1
67                        ari                         scanorama               gtex_v9      1
68                        ari                         scanorama               hypomap      1
69                        ari                         scanorama     immune_cell_atlas      1
70                        ari                         scanorama  mouse_pancreas_atlas      1
71                        ari                         scanorama        tabula_sapiens      1
72                        ari                            scanvi                   dkd      1
73                        ari                            scanvi               gtex_v9      1
74                        ari                            scanvi               hypomap      1
75                        ari                            scanvi     immune_cell_atlas      1
76                        ari                            scanvi  mouse_pancreas_atlas      1
77                        ari                            scanvi        tabula_sapiens      1
78                        ari                              scvi                   dkd      1
79                        ari                              scvi               gtex_v9      1
80                        ari                              scvi               hypomap      1
81                        ari                              scvi     immune_cell_atlas      1
82                        ari                              scvi  mouse_pancreas_atlas      1
83                        ari                              scvi        tabula_sapiens      1
84                        ari               shuffle_integration                   dkd      1
85                        ari               shuffle_integration               gtex_v9      1
86                        ari               shuffle_integration               hypomap      1
87                        ari               shuffle_integration     immune_cell_atlas      1
88                        ari               shuffle_integration  mouse_pancreas_atlas      1
89                        ari               shuffle_integration        tabula_sapiens      1
90                        ari  shuffle_integration_by_cell_type                   dkd      1
91                        ari  shuffle_integration_by_cell_type               gtex_v9      1
92                        ari  shuffle_integration_by_cell_type               hypomap      1
93                        ari  shuffle_integration_by_cell_type     immune_cell_atlas      1
94                        ari  shuffle_integration_by_cell_type  mouse_pancreas_atlas      1
95                        ari  shuffle_integration_by_cell_type        tabula_sapiens      1
96                        ari                               uce                   dkd      1
97                        ari                               uce               gtex_v9      1
98                        ari                               uce               hypomap      1
99                        ari                               uce     immune_cell_atlas      1
100                       ari                               uce  mouse_pancreas_atlas      1
101                       ari                               uce        tabula_sapiens      1
102                 ari_batch                 batchelor_fastmnn                   dkd      1
103                 ari_batch                 batchelor_fastmnn               gtex_v9      1
104                 ari_batch                 batchelor_fastmnn               hypomap      1
105                 ari_batch                 batchelor_fastmnn     immune_cell_atlas      1
106                 ari_batch                 batchelor_fastmnn  mouse_pancreas_atlas      1
107                 ari_batch                 batchelor_fastmnn        tabula_sapiens      1
108                 ari_batch                            combat                   dkd      1
109                 ari_batch                            combat               gtex_v9      1
110                 ari_batch                            combat               hypomap      1
111                 ari_batch                            combat     immune_cell_atlas      1
112                 ari_batch                            combat  mouse_pancreas_atlas      1
113                 ari_batch                            combat        tabula_sapiens      1
114                 ari_batch                  embed_cell_types                   dkd      1
115                 ari_batch                  embed_cell_types               gtex_v9      1
116                 ari_batch                  embed_cell_types               hypomap      1
117                 ari_batch                  embed_cell_types     immune_cell_atlas      1
118                 ari_batch                  embed_cell_types  mouse_pancreas_atlas      1
119                 ari_batch                  embed_cell_types        tabula_sapiens      1
120                 ari_batch         embed_cell_types_jittered                   dkd      1
121                 ari_batch         embed_cell_types_jittered               gtex_v9      1
122                 ari_batch         embed_cell_types_jittered               hypomap      1
123                 ari_batch         embed_cell_types_jittered     immune_cell_atlas      1
124                 ari_batch         embed_cell_types_jittered  mouse_pancreas_atlas      1
125                 ari_batch         embed_cell_types_jittered        tabula_sapiens      1
126                 ari_batch                           harmony                   dkd      1
127                 ari_batch                           harmony               gtex_v9      1
128                 ari_batch                           harmony               hypomap      1
129                 ari_batch                           harmony     immune_cell_atlas      1
130                 ari_batch                           harmony  mouse_pancreas_atlas      1
131                 ari_batch                           harmony        tabula_sapiens      1
132                 ari_batch                         harmonypy                   dkd      1
133                 ari_batch                         harmonypy               gtex_v9      1
134                 ari_batch                         harmonypy               hypomap      1
135                 ari_batch                         harmonypy     immune_cell_atlas      1
136                 ari_batch                         harmonypy  mouse_pancreas_atlas      1
137                 ari_batch                         harmonypy        tabula_sapiens      1
138                 ari_batch                             liger                   dkd      1
139                 ari_batch                             liger               gtex_v9      1
140                 ari_batch                             liger               hypomap      1
141                 ari_batch                             liger     immune_cell_atlas      1
142                 ari_batch                             liger  mouse_pancreas_atlas      1
143                 ari_batch                             liger        tabula_sapiens      1
144                 ari_batch                    no_integration                   dkd      1
145                 ari_batch                    no_integration               gtex_v9      1
146                 ari_batch                    no_integration               hypomap      1
147                 ari_batch                    no_integration     immune_cell_atlas      1
148                 ari_batch                    no_integration  mouse_pancreas_atlas      1
149                 ari_batch                    no_integration        tabula_sapiens      1
150                 ari_batch              no_integration_batch                   dkd      1
151                 ari_batch              no_integration_batch               gtex_v9      1
152                 ari_batch              no_integration_batch               hypomap      1
153                 ari_batch              no_integration_batch     immune_cell_atlas      1
154                 ari_batch              no_integration_batch  mouse_pancreas_atlas      1
155                 ari_batch              no_integration_batch        tabula_sapiens      1
156                 ari_batch                           pyliger                   dkd      1
157                 ari_batch                           pyliger               gtex_v9      1
158                 ari_batch                           pyliger               hypomap      1
159                 ari_batch                           pyliger     immune_cell_atlas      1
160                 ari_batch                           pyliger  mouse_pancreas_atlas      1
161                 ari_batch                           pyliger        tabula_sapiens      1
162                 ari_batch                            scalex                   dkd      1
163                 ari_batch                            scalex               gtex_v9      1
164                 ari_batch                            scalex               hypomap      1
165                 ari_batch                            scalex     immune_cell_atlas      1
166                 ari_batch                            scalex  mouse_pancreas_atlas      1
167                 ari_batch                            scalex        tabula_sapiens      1
168                 ari_batch                         scanorama                   dkd      1
169                 ari_batch                         scanorama               gtex_v9      1
170                 ari_batch                         scanorama               hypomap      1
171                 ari_batch                         scanorama     immune_cell_atlas      1
172                 ari_batch                         scanorama  mouse_pancreas_atlas      1
173                 ari_batch                         scanorama        tabula_sapiens      1
174                 ari_batch                            scanvi                   dkd      1
175                 ari_batch                            scanvi               gtex_v9      1
176                 ari_batch                            scanvi               hypomap      1
177                 ari_batch                            scanvi     immune_cell_atlas      1
178                 ari_batch                            scanvi  mouse_pancreas_atlas      1
179                 ari_batch                            scanvi        tabula_sapiens      1
180                 ari_batch                              scvi                   dkd      1
181                 ari_batch                              scvi               gtex_v9      1
182                 ari_batch                              scvi               hypomap      1
183                 ari_batch                              scvi     immune_cell_atlas      1
184                 ari_batch                              scvi  mouse_pancreas_atlas      1
185                 ari_batch                              scvi        tabula_sapiens      1
186                 ari_batch               shuffle_integration                   dkd      1
187                 ari_batch               shuffle_integration               gtex_v9      1
188                 ari_batch               shuffle_integration               hypomap      1
189                 ari_batch               shuffle_integration     immune_cell_atlas      1
190                 ari_batch               shuffle_integration  mouse_pancreas_atlas      1
191                 ari_batch               shuffle_integration        tabula_sapiens      1
192                 ari_batch  shuffle_integration_by_cell_type                   dkd      1
193                 ari_batch  shuffle_integration_by_cell_type               gtex_v9      1
194                 ari_batch  shuffle_integration_by_cell_type               hypomap      1
195                 ari_batch  shuffle_integration_by_cell_type     immune_cell_atlas      1
196                 ari_batch  shuffle_integration_by_cell_type  mouse_pancreas_atlas      1
197                 ari_batch  shuffle_integration_by_cell_type        tabula_sapiens      1
198                 ari_batch                               uce                   dkd      1
199                 ari_batch                               uce               gtex_v9      1
200                 ari_batch                               uce               hypomap      1
201                 ari_batch                               uce     immune_cell_atlas      1
202                 ari_batch                               uce  mouse_pancreas_atlas      1
203                 ari_batch                               uce        tabula_sapiens      1
204                 asw_batch                 batchelor_fastmnn                   dkd      1
205                 asw_batch                 batchelor_fastmnn               gtex_v9      1
206                 asw_batch                 batchelor_fastmnn               hypomap      1
207                 asw_batch                 batchelor_fastmnn     immune_cell_atlas      1
208                 asw_batch                 batchelor_fastmnn  mouse_pancreas_atlas      1
209                 asw_batch                 batchelor_fastmnn        tabula_sapiens      1
210                 asw_batch                            combat                   dkd      1
211                 asw_batch                            combat               gtex_v9      1
212                 asw_batch                            combat               hypomap      1
213                 asw_batch                            combat     immune_cell_atlas      1

In [70]:
# 1. List all unique metrics
metrics_left = filtered_df["metric_id"].unique()

print("The metrics left in filtered_df:")
for m in metrics_left:
    print(f"  • {m}")

print("\nThe methods left for each metric:")

# 2. For each metric, list its methods
for metric in metrics_left:
    methods = (
        filtered_df.loc[filtered_df.metric_id == metric, "method_id"]
        .unique()
    )
    methods = sorted(methods)
    methods_list = ", ".join(methods)
    print(f"  • {metric}: {methods_list}")

The metrics left in filtered_df:
  • ari
  • asw_batch
  • asw_label
  • cell_cycle_conservation
  • clisi
  • graph_connectivity
  • ilisi
  • isolated_label_f1
  • nmi
  • pcr

The methods left for each metric:
  • ari: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • asw_batch: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • asw_label: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • cell_cycle_conservation: batchelor_fastmnn, combat, embed_cell_types, harmony, harmonypy, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • clisi: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • graph_connectivity: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • ilisi: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • isolated_label_f1: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • nmi: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type
  • pcr: batchelor_fastmnn, combat, embed_cell_types, embed_cell_types_jittered, harmony, harmonypy, liger, no_integration, no_integration_batch, scanorama, scanvi, scvi, shuffle_integration, shuffle_integration_by_cell_type

In [73]:
# check if the methods left are same
methods_per_metric = (
    filtered_df.groupby("metric_id")["method_id"]
    .apply(lambda x: frozenset(x.unique()))
)

# Are they all identical?
all_same = methods_per_metric.nunique() == 1

print("Do all metrics have the same methods left?:", all_same)

Do all metrics have the same methods left?: False

In [75]:
# Convert frozensets → sets for intersection math
method_sets = list(map(set, methods_per_metric))

# ---- 1️⃣ Methods in ALL metrics ----
methods_in_all_metrics = set.intersection(*method_sets)

print("Methods present in ALL metrics:")
print(sorted(methods_in_all_metrics))

# ---- 2️⃣ Methods in ONLY SOME metrics ----
methods_in_any_metric = set.union(*method_sets)
methods_in_some_metrics = methods_in_any_metric - methods_in_all_metrics

print("\nMethods present in ONLY SOME metrics:")
print(sorted(methods_in_some_metrics))

Methods present in ALL metrics:
['batchelor_fastmnn', 'combat', 'embed_cell_types', 'harmony', 'harmonypy', 'no_integration', 'no_integration_batch', 'scanorama', 'scvi', 'shuffle_integration', 'shuffle_integration_by_cell_type']

Methods present in ONLY SOME metrics:
['embed_cell_types_jittered', 'liger', 'scanvi']